version: '3'
services:
  db:
    image: mysql:latest
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: trust

  api:
    image: josafat/api-rest
    command: sh -c "ls && ./wait-db.sh db python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/api-rest-hnp
    ports:
      - "8000:8000"