version: '3'
services:
  db:
    image: mysql:latest
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: trust
    restart: always

  api:
    image: josafat/api-rest
    command: sh -c "ls && ./wait-db.sh db python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - env_vars.env
    volumes:
      - .:/api-rest-hnp
    ports:
      - "8000:8000"
    
  app-frontend:
    image: josafat/bhnp
    ports:
      - "80:80"
    restart: always