# Generated by Django 5.0.3 on 2024-04-03 22:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('ventas_semana', models.IntegerField(default=0)),
                ('supermodel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('venta_id', models.IntegerField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha', models.TimeField(default=django.utils.timezone.now, editable=False)),
                ('user_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='APIRest.usuario')),
            ],
        ),
    ]
