# Generated by Django 5.0.4 on 2024-04-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIRest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='venta_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
