# Generated by Django 5.0.3 on 2024-04-25 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIRest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
