# Generated by Django 5.0.3 on 2024-04-15 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIRest', '0002_rename_active_venta_is_active_usuario_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='monto',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='fecha',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='cantidad',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='venta_id',
            new_name='sale_id',
        ),
    ]
