# Generated by Django 5.0.3 on 2024-04-04 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIRest', '0003_alter_usuario_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
