# Generated by Django 5.0.3 on 2024-04-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIRest', '0003_remove_sale_is_active_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sale_id',
            new_name='id',
        ),
    ]
