# Generated by Django 5.0.3 on 2024-04-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIRest', '0004_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='monto',
            field=models.FloatField(default=0),
        ),
    ]
