# Generated by Django 5.0.3 on 2024-04-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIRest', '0005_alter_venta_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
