# Generated by Django 5.0.3 on 2024-04-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIRest', '0006_alter_usuario_correo_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
