# Etapa 1: Construir la aplicación
FROM node:lts-alpine3.20 AS build

WORKDIR /WebAdministrator

COPY package*.json /WebAdministrator/

RUN npm install

COPY . /WebAdministrator/

RUN npm run build

RUN ls -la /WebAdministrator

RUN ls -la /WebAdministrator/dist

# Etapa 2: Servir la aplicación con Nginx
FROM nginx:stable-perl

WORKDIR /usr/share/nginx/html

COPY --from=build /WebAdministrator/dist .

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]
